amyeroberts/transformers

- src/transformers/models/clip/feature_extraction_clip.py
- tests/models/clip/test_feature_extraction_clip.py
Reverts amyeroberts/transformers#22
> Revert "Type cast before normalize clip"

- src/transformers/models/convnext/feature_extraction_convnext.py
- tests/models/convnext/test_feature_extraction_convnext.py
Reverts amyeroberts/transformers#13
> Revert "Type cast before normalize convnext"

- src/transformers/models/deit/feature_extraction_deit.py
- tests/models/deit/test_feature_extraction_deit.py
Reverts amyeroberts/transformers#14
> Revert "Type cast before normalize deit"

- src/transformers/models/detr/feature_extraction_detr.py
- tests/models/detr/test_feature_extraction_detr.py
Reverts amyeroberts/transformers#1
> Revert "Type cast before normalize detr"

- src/transformers/models/dpt/feature_extraction_dpt.py
- tests/models/dpt/test_feature_extraction_dpt.py
Reverts amyeroberts/transformers#15
> Revert "Type cast before normalize dpt"

- src/transformers/models/flava/feature_extraction_flava.py
- tests/models/flava/test_feature_extraction_flava.py
Reverts amyeroberts/transformers#17
> Revert "Type cast before normalize flava"

- src/transformers/models/glpn/feature_extraction_glpn.py
- tests/models/glpn/test_feature_extraction_glpn.py
Reverts amyeroberts/transformers#18
> Revert "Type cast before normalize glpn"

- src/transformers/models/imagegpt/feature_extraction_imagegpt.py
- tests/models/imagegpt/test_feature_extraction_imagegpt.py
Reverts amyeroberts/transformers#2
> Revert "Type cast before normalize imagegpt"

- src/transformers/models/layoutlmv2/feature_extraction_layoutlmv2.py
- tests/models/layoutlmv2/test_feature_extraction_layoutlmv2.py
Reverts amyeroberts/transformers#19
> Revert "Type cast before normalize layoutlmv2"

- src/transformers/models/layoutlmv3/feature_extraction_layoutlmv3.py
- tests/models/layoutlmv3/test_feature_extraction_layoutlmv3.py
Reverts amyeroberts/transformers#20
> Revert "Type cast before normalize layoutlmv3"

- src/transformers/models/levit/feature_extraction_levit.py
- tests/models/levit/test_feature_extraction_levit.py
Reverts amyeroberts/transformers#3
> Revert "Type cast before normalize levit"

- src/transformers/models/maskformer/feature_extraction_maskformer.py
- tests/models/maskformer/test_feature_extraction_maskformer.py
Reverts amyeroberts/transformers#4
> Revert "Type cast before normalize maskformer"

- src/transformers/models/mobilevit/feature_extraction_mobilevit.py
- tests/models/mobilevit/test_feature_extraction_mobilevit.py
Reverts amyeroberts/transformers#21
> Revert "Type cast before normalize mobilevit"

- src/transformers/models/owlvit/feature_extraction_owlvit.py
- tests/models/owlvit/test_feature_extraction_owlvit.py
Reverts amyeroberts/transformers#5
> Revert "Type cast before normalize owlvit"

- src/transformers/models/poolformer/feature_extraction_poolformer.py
- tests/models/poolformer/test_feature_extraction_poolformer.py
Reverts amyeroberts/transformers#7
> Revert "Type cast before normalize poolformer"

- src/transformers/models/segformer/feature_extraction_segformer.py
- tests/models/segformer/test_feature_extraction_segformer.py
Reverts amyeroberts/transformers#8
> Revert "Type cast before normalize segformer"

- src/transformers/models/vilt/feature_extraction_vilt.py
- tests/models/vilt/test_feature_extraction_vilt.py
Reverts amyeroberts/transformers#10
> Revert "Type cast before normalize vilt"

- src/transformers/models/vit/feature_extraction_vit.py
- tests/models/vit/test_feature_extraction_vit.py
Reverts amyeroberts/transformers#16
> Revert "Type cast before normalize vit"

- src/transformers/models/yolos/feature_extraction_yolos.py
- tests/models/yolos/test_feature_extraction_yolos.py
Reverts amyeroberts/transformers#11
> Revert "Type cast before normalize yolos"

- src/transformers/models/perceiver/feature_extraction_perceiver.py
Reverts amyeroberts/transformers#6
> Revert "Type cast before normalize perceiver"

- src/transformers/generation_tf_logits_process.py
- src/transformers/generation_tf_utils.py
- src/transformers/models/whisper/modeling_tf_whisper.py
- tests/generation/test_generation_tf_logits_process.py
> TF Whisper: XLA enabled

- src/transformers/models/fuyu/image_processing_fuyu.py
- src/transformers/models/fuyu/processing_fuyu.py
Replaces https://github.com/huggingface/transformers/pull/27083
> Fuyu processing: handle coordinates
